markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: 
author: ""
email: 
name: "My Blog"
url: moonbrillante.github.io
domain: moonbrillante.github.io
all_categories: [
["leetcode","Leetcode刷题","/posts/leetcode.html"], 
["python","Python","/posts/python.html"],
["web crawler","Web爬虫","/posts/crawling.html"],
["data science","Data Science","/posts/data_science.html"],
["etl", "ETL","/posts/etl.html"], 
["machine learning","Machine Learning","/posts/machine_learning.html"],
["big data","Big Data","/posts/big_data.html"], 
["web","Web网站","/posts/web.html"],
["other","Django","/posts/other.html"],
["about","About","/about.html"],
]
paginate: 8
paginate_path: "posts/page:num"
timezone: Europe/Madrid

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
