markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: panxw
author: "潘学文"
email: winfirm#163.com
name: "潘学文个人博客"
url: http://www.panxw.com
domain: www.panxw.com
all_categories: [
["leetcode", "Leetcode刷题","/posts/android.html"], 
["python crawling", "python crawling","/posts/program.html"],
["ETL", "ETL笔记","/posts/web.html"], 
["machine learniing", "Machine Learning机器学习","/posts/linux.html"],
["big data", "Big Data","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
